### ISSUE TITLE
Do-notation

### ISSUE THREAD

**Issue by ostera** [cyrus-/relit#14]
Hello!

There's recently been several threads around the Reason syntax repo and related `ppx`'s for supporting the equivalent (or something fulfilling a subset of the requirements) of Haskell's `do-notation`.

It'd be a very interesting point in this conversation to be able to have/showcase a sample/standard do-notation available to use with `relit`. 

Mark this as a #feature-request, but I'd be interested in looking into it.

**Comment by cyrus-** [comment]
Hey Leandro!

You actually can't quite express do-notation using TLMs because it is a new binding construct -- the capture avoidance restriction prevents you from binding the variables to the left of the `<-` in spliced expressions.

You could possibly do something like 

```
$do `(
  command1;
  x => command2;
  y => command3;
  return command4
)`
```

Here, you're just using Reason's anonymous function notation for the purposes of binding the result of the _previous_ line. I'm not sure if that's entirely satisfying.

**Comment by cyrus-** [comment]
Actually, maybe that won't even work because you don't know what the types of `x` and `y` are a priori.

I think do notation might be a situation where, because you're changing the binding structure of the syntax, it makes sense to actually build it into Reason?
