### ISSUE TITLE
dune ppx support

### ISSUE THREAD

**Issue by struktured** [cyrus-/relit#6]
Is this being worked on? Has anyone documented why it doesn't work yet? Using `relit` with my ocaml / dune project would be a huge boon for my team.

**Comment by charlesetc** [comment]
Dune working with Relit would be awesome! Relit works by typechecking within a PPX, which requires being passed a list of ocaml object files (.cmo, .cma) from the build system. This works fine when run as a classical PPX; ocamlc is passed a `-ppx` option and it passes on the right object files to Relit.

Dune [doesn't support classical ppx](https://dune.readthedocs.io/en/latest/advanced-topics.html#classical-ppx). Instead, I believe it does all the preprocessing ahead of time, and then calls `ocamlc` on the already preprocessed files. I've heard this is a big performance win because it can do the preprocessing in one go, instead of calling each ppx as a separate process.

Since Relit does need those object files to run, I don't think it'll ever work in this environment. (The workaround [ppxfind](https://github.com/diml/ppxfind) also didn't help when I tried: I think it wraps a PPX executable to be used within a driver, which still doesn't have the object files.)

There is some hope: Relit could be slightly refactored to be a [compiler plugin](https://caml.inria.fr/pub/docs/manual-ocaml/plugins.html) instead of a PPX. I haven't seen much documentation about these beside that page, so I'm not sure how supported they are. There's also the possibility that dune supports/will support passing arbitrary compiler flags or straight up supports classical ppx in the future. I don't know how likely that is. Overall, the chances of Relit working with Dune seems pretty low in the near future, but it's also been a couple months since I've done any research so I'll try looking into it again soon!

**Comment by struktured** [comment]
@rgrinberg- you have any thoughts on the feasibility of this?

**Comment by rgrinberg** [comment]
> Dune doesn't support classical ppx. Instead, I believe it does all the preprocessing ahead of time, and then calls ocamlc on the already preprocessed files. I've heard this is a big performance win because it can do the preprocessing in one go, instead of calling each ppx as a separate process.

The `staged_pps` option should help you get around the problem of being forced to do the preprocessing before any compilation. See the docs here: https://dune.readthedocs.io/en/latest/dune-files.html?highlight=staged_pps#preprocessing-specification

**Comment by charlesetc** [comment]
Woah that's awesome! I'll take a longer look soon

**Comment by charlesetc** [comment]
This works! I've changed the test suite and the examples to use dune. :tada:  It took a [small bug fix](https://github.com/ocaml/dune/pull/1384) in dune, so we require installing the very latest version of dune until the fix gets onto opam.
